# -*- coding: utf-8 -*-
"""AIML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14n-F5btE-7laRP5m8d87t-hr2eZOamyM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/parkinsons.csv')

df.head()

df.tail()

df.shape

df.describe()

df.isna().sum()

import seaborn as sns
import matplotlib.pyplot as plt

numeric_df = df.select_dtypes(include='number')
correlations = numeric_df.corr()
sns.heatmap(correlations, square=True, annot_kws={'size': 15})
plt.yticks(rotation=0)
plt.xticks(rotation=0)
plt.show()

new_df = df[['MDVP:Fo(Hz)','MDVP:Fhi(Hz)','MDVP:Flo(Hz)','MDVP:Jitter(%)','MDVP:Jitter(Abs)','MDVP:PPQ','MDVP:Shimmer','NHR']].copy()

x=new_df

print(x)

y=df['status']

print(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

"""Random Forest Classification"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(criterion = 'entropy', max_depth = 20, n_estimators = 100)
rf.fit(X_train,y_train)

y_pred_rf = rf.predict(X_test)
y_pred_rf

from sklearn.metrics import accuracy_score

score_rf = round(accuracy_score(y_pred_rf,y_test)*100,2)
print("The accuracy score achieved using the Random Forest model is: "+str(score_rf)+" %")

from sklearn.metrics import confusion_matrix, classification_report
from yellowbrick.classifier import ConfusionMatrix

rf_cm = ConfusionMatrix(rf, cmap='GnBu')

rf_cm.fit(X_train, y_train)
rf_cm.score(X_test, y_test)
rf_cm.show()

print(classification_report(y_test, y_pred_rf))

"""KNN algorithm"""

from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5 )
classifier.fit(X_train, y_train)

y_pred_knn = classifier.predict(X_test)
y_pred_knn

from sklearn.metrics import accuracy_score

score_knn = round(accuracy_score(y_pred_knn,y_test)*100,2)
print("The accuracy score achieved using the K-Nearest Neighbor model is: "+str(score_knn)+" %")

"""SVM algorithm"""

from sklearn.svm import SVC # "Support vector classifier"
svc= SVC(kernel='linear', random_state=0)
svc.fit(X_train, y_train)

y_pred_svm= svc.predict(X_test)
y_pred_svm

from sklearn.metrics import accuracy_score

score_svm = round(accuracy_score(y_pred_svm,y_test)*100,2)
print("The accuracy score achieved using the SVM Algorithm is: "+str(score_svm)+" %")

import pickle

filename = "AIML Project.sav"
pickle.dump(rf, open(filename, 'wb'))

model = pickle.load(open('AIML Project.sav', 'rb'))