# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4-Gm-h1W5N5QW2ALGQTg_fiJQafUYL9
"""

import subprocess

subprocess.check_call(['pip', 'install', 'streamlit', '-q'])

!streamlit --version

!wget -q -O - ipv4.icanhazip.com

!npm install -g localtunnel

!lt --help

!streamlit run final_project.py & npx localtunnel --port 8501